##### McGill University
##### R Tutorial
##### Guilherme D. Garcia

#############
### DAY 3 ###
#############


# Data visualization

# Today's topic is related to Exploratory Data Analysis (EDA),
# which is usually the step that comes before the statistical analysis.

# We'll be using ggplot2, a widely used R package for plotting data.
# Other packages are also quite useful: graphics, rCharts, lattice etc.
# These packages do similar things, but some offer more tools.
# ggplot2 has a *huge* library of plots. Crucially, it has a very
# nice documentation (also, because it's used a lot, you will find
# many forums/websites about it)

# This time we'll use the english data set, from
# the languageR package. There are continuous and categorical
# variables in the data, and that's useful for plotting

# NB: Last time we also had some EDA, when we used xtabs etc.


# Load the packages:

library(ggplot2)
library(languageR)
library(plyr)
library(scales) # for % in plots

data(english)

# Let's use a very short name for our data this time

d = english

# This dataset has a lot of columns, so let's first create a 
# more concise version (we'll overwrite d).

names(d)

columns = c("RTlexdec", "Familiarity", "Word", "AgeSubject", "LengthInLetters", "CV", "Obstruent", "Voice")

d = d[,columns]

head(d)

# This looks good for plotting.

# RTlexdec: numeric vector of the log RT in visual lexical decision

# This will be our variable of interest (response), so we'll be
# plotting other variables as possible predictors of RTlexdec.

###### EXERCISE

### Review from last time (also related to EDA)


# In what follows, create a code that explores each question.
# You'll need xtabs(), prop.table() and ddply().

head(d)

# What's the proportion of voiced and voiceless segments
# (initial phoneme)?




# Create a contingency table that includes Voice and CV. % by Voice.
# (ignore the obvious correlation here)






# Create a data frame that shows the mean RT and the mean Familiarity
# by AgeSubject and LengthInLetters. What impact do these two
# variables have on the mean reaction time? How about Familiarity and 
# LengthInLetters?








#############################################
#############################################
#############################################


# GGPLOT2: http://docs.ggplot2.org/



### ggplot syntax

# There are two main ways to use ggplot. The quick method 
# (less intuitive), and the longer method (easier to remember)

# 1. qplot() is the 'quick version'

# Read about it here: http://docs.ggplot2.org/0.9.3/qplot.html


################# FUNDAMENTALS





################# SCATTER PLOT 



# INCREMENTAL example: qplot(variable1, variable2, data)


# Let's plot RTlexdec as a function of Familiarity (and other vars)

qplot(Familiarity, RTlexdec, data=d)

qplot(Familiarity, RTlexdec, data=d, colour=AgeSubject)

qplot(Familiarity, RTlexdec, data=d, colour=AgeSubject, size=LengthInLetters)

qplot(Familiarity, RTlexdec, data=d, colour=AgeSubject, size=LengthInLetters, alpha=0.1)

qplot(Familiarity, RTlexdec, data=d, colour=AgeSubject, size=LengthInLetters, alpha=I(0.2), facets = Voice ~ Obstruent)


# 2. ggplot() is the longer version

# Same INCREMENTAL example: ggplot(data, aes(axes)) + ...

ggplot(data=d, aes(x=Familiarity, y=RTlexdec)) + geom_point()

ggplot(data=d, aes(x=Familiarity, y=RTlexdec, color=AgeSubject)) + geom_point()

ggplot(data=d, aes(x=Familiarity, y=RTlexdec, color=AgeSubject, size=LengthInLetters)) + geom_point()

ggplot(data=d, aes(x=Familiarity, y=RTlexdec, color=AgeSubject, size=LengthInLetters)) + geom_point(alpha=0.2)

ggplot(data=d, aes(x=Familiarity, y=RTlexdec, color=AgeSubject, size=LengthInLetters)) + geom_point(alpha=0.2) + facet_grid(Voice ~ Obstruent)

# The titles in each facet will be inherited from the factor levels
# So you can change them if you wish.

# Alpha goes from 0 to 1.

# You can see that creating a plot with ggplot() is like adding
# components.

# First, you tell R the basics (data and axes)

# Then, you choose the method: scatter plots = geom_point()


# Each TYPE of plot you wish to create is generated by a geom_...():

# boxplot: 		+ geom_boxplot()
# histograms: 		+ geom_histogram()
# bar plots: 		+ geom_bar()
# scatter plots: 	+ geom_point()
# spread points: 	+ geom_jitter()
# lines: 		+ geom_line()
# violin plots: 	+ geom_violin()
# density plots:	+ geom_density()
# text plots:		+ geom_text()
# etc.

# annotation:		+ annotate()

# pie charts: 		+ coord_polar()

# Check http://docs.ggplot2.org/ for a full list


# In fact, you can add layers that don't necessarily make sense,
# but this shows you the amount of control that you have:


ggplot(data=d, (aes(x=AgeSubject, y=RTlexdec))) + geom_jitter(color='brown', alpha=0.3) + geom_boxplot() + geom_violin(alpha=0.3, fill='blue')

# This plot is just totally off, but it's generated without warnings
# or errors. Layering is a great aspect of plotting in R, but R won't
# tell you which plots make more/less sense.

# Also, note that layers are built in the order you add them.


############### Density plots

ggplot(data=d, aes(x=RTlexdec)) + geom_density(fill="blue", color="blue", alpha=0.5) + geom_rug() 

# You can flip your plot by adding + coord_flip():

ggplot(data=d, aes(x=RTlexdec)) + geom_density(fill="blue", color="blue", alpha=0.5) + geom_rug() + coord_flip()

# Whenever you want to know which arguments a geom_ takes:
# type ? geom_...
# Usually, google will be more useful, though.


# This plots the density of RTlexdec and also adds a geom_rug(), so
# you can see where the data points are more concentrated

############### Boxplots

# Let's say you have a categorical variable in the x axis and a 
# continuous variable in the y axis.

ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot()

# What if you want to add the data points on top of the boxplot?

ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot() + geom_jitter()

# This doesn't look that great, though. Add transparency (alpha):

ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot() + geom_jitter(alpha=0.1)

# Adding facets to check for interactions

ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot() + geom_jitter(alpha=0.1) + facet_grid(~CV)


############### Barplots

# Histogram

# geom_bar() and geom_histogram() can give you the same output


ggplot(data=d, aes(x=Obstruent, y=(..count..)/sum(..count..))) + geom_bar() + scale_y_continuous(labels = percent_format()) + labs(x="Type of segment", y="%")

ggplot(data=d, aes(x=Obstruent, y=(..count..)/sum(..count..))) + geom_histogram() + scale_y_continuous(labels = percent_format()) + labs(x="Type of segment", y="%")



# Adding ERROR BARS (standard error): a manual way to do it
# You probably won't add error bars like this, so this is just
# to show you how you could in principle do it.

# First, we need to create a function that calculates std errors:

sem = function(x){
	n = sum(x,na.rm=T)/mean(x,na.rm=T)
	sqrt(var(x, na.rm=T)/n)
}

# Don't worry about syntax here; we'll look into functions next time.


head(d)

# Now we'll extract the mean RTlexdec by age group:

data = ddply(d,.(AgeSubject), summarise, meanRT = mean(RTlexdec))

# Finally, we'll add the std errors to our new data frame.


data$SE = NA

data[1,'SE'] = sem(d[d$AgeSubject == 'old',]$RTlexdec)
data[2,'SE'] = sem(d[d$AgeSubject == 'young',]$RTlexdec)

# This is what our input looks like now:

data

ggplot(data=data, aes(x=AgeSubject, y=meanRT)) + geom_errorbar(width = 0.2, aes(ymax = meanRT + SE, ymin = meanRT - SE)) + geom_bar(stat='identity', alpha=0.4)

# You can see error bars are tiny here (note the y-axis scale)

# You can also only use a point + error bars, which makes more sense:

ggplot(data=data, aes(x=AgeSubject, y=meanRT)) + geom_errorbar(width = 0.2, aes(ymax = meanRT + SE, ymin = meanRT - SE)) + geom_point()

# Read more: http://docs.ggplot2.org/0.9.3.1/geom_errorbar.html

# Also: whenever you have you a question on ggplot2, google it.
# A good place: http://stackoverflow.com/questions/tagged/ggplot2


######################## BUT:

# YOU DON'T NEED TO DO IT MANUALLY:

ourPlot = ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) 

# Let's assign the basic bit of the plot to a variable to be concise


# Plotting sd:

ourPlot + stat_summary(fun.y = sd, geom = "point", position="dodge", size=4, shape=5)

# Plotting mean: (ylab will be adjusted)

ourPlot + stat_summary(fun.y = mean, geom = "point", position="dodge", size=4, shape=5)

# ERROR BAR:

ourPlot + stat_summary(fun.data = mean_cl_normal, geom = "errorbar", width=0.1) 

# How would you create the same plot as a function of the CV variable?






# As you can see, stat_summary() is incredibly useful.



######### Text and annotation

# Note: Many of the examples that follow wouldn't normally be used.

###### Text instead of points

# Let's say you want to plot the actual words (i.e., values of a var).
# You also want to add a green (!) trend line.

ggplot(data=d[d$LengthInLetters==3,], aes(x=Familiarity, y=RTlexdec)) + geom_text(aes(label=Word), alpha=0.5) + geom_smooth(color="green", size=2)

# geom_smooth() also includes the standard error (gray area). You
# can remove it, though.

ggplot(data=d[d$LengthInLetters==3,], aes(x=Familiarity, y=RTlexdec)) + geom_text(aes(label=Word), alpha=0.5) + geom_smooth(color="green", size=2, se=F)

# You can also use other statistical methods to define the trend line.
# For example, let's say you want to use a (linear) regression line:

ggplot(data=d[d$LengthInLetters==3,], aes(x=Familiarity, y=RTlexdec)) + geom_text(aes(label=Word), alpha=0.5) + geom_smooth(color="green", size=2, method='lm')


###### Annotation

What if you want to write on your plot?


ggplot(data=d[d$LengthInLetters==3,], aes(x=Familiarity, y=RTlexdec)) + geom_text(aes(label=Word), alpha=0.5) + geom_smooth(color="green", size=2) + annotate("text", x=6, y=7, label="Test", fontface="bold", size=9, color="red")

# So you can provide x and y coordinates, fontsize, color etc. 




############ Formatting

# Visit http://docs.ggplot2.org/0.9.2.1/theme.html


##### Title and labels


ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot() + geom_jitter(alpha=0.1) + ggtitle("My plot") + ylab("log(RT)") + xlab("Subject age")

##### Colors (http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/)

## The package RColorBrewer is amazing, so if you're into colors,
## check it out.

ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot() + geom_jitter(alpha=0.1, color="blue") + ggtitle("My plot") + ylab("log(RT)") + xlab("Subject age")

ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot() + geom_jitter(alpha=0.2, aes(color=Voice)) + ggtitle("My plot") + ylab("log(RT)") + xlab("Subject age")

# You can always change the colors, of course 
# (you can even create your own)


##### Background

# *Everything* about ggplot can be formatted. You might want to
# have a white background (better for publication):

ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot() + geom_jitter(alpha=0.1) + ggtitle("My plot") + ylab("log(RT)") + xlab("Subject age") + theme_bw()

# You can play around with the arguments in geom_boxplot().

ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot(fill="lightblue") + geom_jitter(alpha=0.1) + ggtitle("My plot") + ylab("log(RT)") + xlab("Subject age") + theme_bw()

# Colors are usually avoided, but sometimes hey can help a lot.

# IMPORTANT: 

## 1. geom_boxplot(aes(THESE ARGUMENTS)) refer to the data

## 2. geom_boxplot(aes(), THESE ARGUMENTS) refer to independent
## parameters

# For example, if you want the plot to be red, use (2). If you want
# colors to represent the age of the subjects, use (1).







##### Spacing

# Again, there are several ways to change the distances in your plot.

# The easiest (simplest) way to add more dist. between labels and the
# plot is by adding \n to your strings.

ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot(width=0.4, size=1) + geom_jitter(alpha=0.1) + ggtitle("My plot\n") + ylab("log(RT)\n") + xlab("Subject age\n") + theme_bw()


# You can also use \n to break lines in labels


ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot() + geom_jitter(alpha=0.1) + ggtitle("My title\nhas two lines\n") + ylab("log(RT)\n") + xlab("Subject age\n") + theme_bw()


# If you google spacing in ggplot, you'll find hundreds of pages.

# If you need something more complete, check the theme() function:

# http://docs.ggplot2.org/0.9.3/theme.html


####### Fonts

# If you don't like R fonts, you'll need to install a package and 
# then load it. Once you've done that, you can use different
# font faces INSIDE theme()

library(extrafont)

# You don't have to do that to change font size, though.

# IMPORTANT: Remember that the font sizes interact with the plot window
# resolution when you save your plot.


ggplot(data=d, aes(x=AgeSubject, y=RTlexdec)) + geom_boxplot() + geom_jitter(alpha=0.1) + ggtitle("My title\nhas two lines\n") + ylab("log(RT)\n") + xlab("Subject age\n") + theme_bw() + theme(text=element_text(size=20, family="CMU Sans Serif"))



